### ISSUE TITLE
How to use another model for android demo

### ISSUE THREAD

**Issue by ilovebioz** [alphacep/vosk-android-demo#101]
Hi,

I would like to replace the current model of vosk android demo with another language model.
- First I try to using the vosk-model-small-vn-0.3 model which provided by alphacep but looks like the content of this model is not the same as the current model in this project. So how can I use it?

- Second, I would like to make another model by myself. As I understood, I can use one project on EGS of Kaldi or a self-making one to generate model then using it to replace the model in this project. If my understanding is correct and assumes I got a Kaldi model, so How can I use it here?

Thank you

**Comment by nshmyrev** [comment]
> First I try to using the vosk-model-small-vn-0.3 model which provided by alphacep but looks like the content of this model is not the same as the current model in this project. So how can I use it?

unpack the files in vosk-android-demo/models/src/main/assets/sync and it should work.

> If my understanding is correct and assumes I got a Kaldi model, so How can I use it here?

you simply put the files into the project, the code should pick them. For more details see the code.

**Comment by nshmyrev** [comment]
Feel free to reopen if you have further questions
