### ISSUE TITLE
Using directly HCLG.fst as decoding graph

### ISSUE THREAD

**Issue by zhao-zilong** [alphacep/vosk-android-demo#104]
Hi Nickolay,
    Thanks for your great work! I tested this demo, it works very well for the numbers, but I want to recognize more complex sentence, so I want to use a bigger lib for example aspire you shared: https://alphacephei.com/vosk/models  in this model, there is only HCLG.fst, but seems the current script does not support to use HCLG.fst directly, I saw you mentioned how to generate Gr.fst in your adaptation page, so do you have the instruction on how to generate HCLr.fst?
    Or is that possible to use directly HCLG.fst to decode wav? I can generate a small HCLG.fst to use.
    Thanks for your attention,
Zilong

**Comment by zhao-zilong** [comment]
Current error I have when I run the Code with HCLG.fst

```
I/VoskAPI: ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
I/VoskAPI: ComputeDerivedVars():ivector-extractor.cc:204) Done.
I/VoskAPI: ReadDataFiles():src/model.cc:235) Loading HCLG from /storage/emulated/0/Android/data/org.vosk.demo/files/sync/model-android/graph/HCLG.fst
I/VoskAPI: ReadDataFiles():src/model.cc:254) Loading words from /storage/emulated/0/Android/data/org.vosk.demo/files/sync/model-android/graph/words.txt
I/VoskAPI: ReadDataFiles():src/model.cc:262) Loading winfo /storage/emulated/0/Android/data/org.vosk.demo/files/sync/model-android/graph/phones/word_boundary.int
W/System: A resource failed to call close. 
E/VoskAPI: KaldiRecognizer():src/kaldi_recognizer.cc:85) Can't create decoding graph
A/libc: /buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError" failed
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9943 (AsyncTask #1), pid 9904 (org.vosk.demo)
```

**Comment by nshmyrev** [comment]
Aspire model doesn't support dynamic graph construction. If you remove words constructor in the code, you can use aspire-like model with hclg.

https://github.com/alphacep/vosk-android-demo/blob/f92790ce4906151e8c5f05787cb947a915932656/app/src/main/java/org/kaldi/demo/KaldiActivity.java#L143

You can also try big daanzu lgraph model, it supports dynamic graph construction and also more accurate than aspire:
https://alphacephei.com/vosk/models/vosk-model-en-us-daanzu-20200905-lgraph.zip

**Comment by nshmyrev** [comment]
Let me know if you have further questions
