### ISSUE TITLE
Dimension mismatch changing model to vosk-model-small-es-0.3

### ISSUE THREAD

**Issue by Neo-Andurin** [alphacep/vosk-android-demo#106]
Hi, I have this problem when I try recognize after to copy the vosk-model-small-es-0.3 content in model-android (and replace files):
![Captura de pantalla 2020-11-12 a las 17 33 09](https://user-images.githubusercontent.com/1114590/98967847-40638a80-250d-11eb-9366-9fa496fc850c.png)

I didn't change any configuration, I just downloaded, replace files, rebuild and try to run.

Thank you!

**Comment by nshmyrev** [comment]
Try to remove files on sdcard in /storage/emulated/0/Android/data/org.vosk.demo/files/sync and run again.

**Comment by Neo-Andurin** [comment]
I have not a sdcard in the phone... I have uninstalled the demo, clean and rebuild the code and install again. Now I get the same with a " --------- beginning of crash":

![Captura de pantalla 2020-11-12 a las 17 46 49](https://user-images.githubusercontent.com/1114590/98969437-21fe8e80-250f-11eb-89d9-8adb0f0a3719.png)

**Comment by nshmyrev** [comment]
Your phone has virtual sdcard anyway, you can remove files with `adb shell`

**Comment by nshmyrev** [comment]
Also it might be that you forgot to update mfcc.conf file inside the model, make sure you copied all the files and deleted old ones.

**Comment by Neo-Andurin** [comment]
I only try to delete all inside model-android and copy the model (instead replace) and its working perfectly.

Thanks!
