### ISSUE TITLE
What is your ProGuard config doing?

### ISSUE THREAD

**Issue by OscarVanL** [alphacep/vosk-android-demo#107]
Hi,

Firstly thanks for this excellent demo, it highlights the functionality in a very clear way 👍

I had a question about your ProGuard config...
https://github.com/alphacep/vosk-android-demo/blob/0d0a3ec212fc37e604c3fde644bf4d4ce045b77a/app/proguard-rules.pro#L1-L3

When I open your demo in Android Studio it says "Unresolved class name".

Does this line do anything, is this error just an IDE mistake?

**Comment by nshmyrev** [comment]
You can disable proguard meanwhile, I'll take a look later.

**Comment by OscarVanL** [comment]
It does not stop the app compiling, I just wondered what the purpose was :)

**Comment by nshmyrev** [comment]
It is not really needed, there are default proguard rules to keep the names of native classes to keep JNI working.
