### ISSUE TITLE
Dutch language in Android

### ISSUE THREAD

**Issue by kmg454** [alphacep/vosk-android-demo#108]
I create the assets/sync/model-android-nl directory and copied the files from the NL model in there.
The app is build without issues but does only recognize English and not Dutch.

What's going wrong here or am i Missing something?

**Comment by nshmyrev** [comment]
Hello. Probably you specified wrong model path in the code. You can check logcat on how files are placed on filesystem and which files are loaded.

**Comment by nshmyrev** [comment]
Dutch model is pretty big btw, it will not work fast enough on Android.

**Comment by kmg454** [comment]
Think the size will be the problem everything else is working fine, do you know an alternative.
At this moment we are using Google speech recognizer but we prefer an offline speech recognizer.

**Comment by nshmyrev** [comment]
You can probably contact [UTwente](https://github.com/opensource-spraakherkenning-nl/) and ask them to rebuild a smaller model
