### ISSUE TITLE
Why was a buffer size of 0.4 seconds worth of samples chosen?

### ISSUE THREAD

**Issue by AdamMakinSoftware** [alphacep/vosk-android-demo#109]
Was just wondering why the buffer length of 0.4 seconds was chosen. Is this the amount of time to make sure that all phonemes are correctly recognised?

**Comment by nshmyrev** [comment]
Too short buffer is slow for kaldi, neural network needs batching for faster computation. Too long buffer is bad for voice activity detection, it skips significant pauses. 0.4 is more or less right although it might need some extra tuning.
