### ISSUE TITLE
How to improve decoding speed

### ISSUE THREAD

**Issue by leeskywolfhot** [alphacep/vosk-android-demo#111]
We want to decode a sentence with dozens of words。Fristly, use recognizeMicrophone function
At the beginning, we used the method of recognizeMicrophone and found that there were many errors in the results. The guess is that the incoming audio is chopped up. Then, using the method of recognizeFile, the recognition results are correct. But the speed is very slow. For example, for 5 seconds of audio, using our own model 113M, it takes 19 seconds to decode. It also takes 17 seconds to use the model provided in the code. Is there any way to increase the decoding speed? What speed may be related to, model size, complexity, vocabulary size, hardware performance, etc.

**Comment by nshmyrev** [comment]
Right, you need a smaller model, take a look on our recent small one and use similar xconfig.

**Comment by leeskywolfhot** [comment]
> Right, you need a smaller model, take a look on our recent small one and use similar xconfig.

Thank you very much!
After we switched to a high-end phone, the decoding speed of the same model and audio was increased by 6 times. Does this mean that the size of the model is not the main factor influencing speed in previous experiments. Generally, is there a recommended size for offline models?

**Comment by nshmyrev** [comment]
> Does this mean that the size of the model is not the main factor influencing speed in previous experiments. Generally, is there a recommended size for offline models?

There are many factors of performance - memory, cpu, etc. Hard to guess without CPU/model information. 

The size of the models we distribute (the small models) is recommended one.
