### ISSUE TITLE
Using Vosk with a USB Digital Audio Input

### ISSUE THREAD

**Issue by OscarVanL** [alphacep/vosk-android-demo#115]
Hi,

We're using a high-quality XLR studio microphone. To connect this, we're using the [iRig Pro IO audio interface](https://www.ikmultimedia.com/products/irigproio/).

This is designed for use on mobile devices, but specifically on Android it has a quirk where it [only works with apps that allow digital input](https://cgi.ikmultimedia.com/ikforum/viewtopic.php?f=9&t=21279).

Do you know how I would support this? I see in the SpeechService class an AudioRecord instance is created, I assume this is where I'd need to change any audio input functionality.

Do you have any experience using USB digital microphone input with Vosk Android?

Thanks.

**Comment by nshmyrev** [comment]
> Do you have any experience using USB digital microphone input with Vosk Android?

No we do not have any experience. Please experiment and let us know.

**Comment by OscarVanL** [comment]
OK our USB C adapter arrived today for this audio interface.

To my pleasant surprise, it worked without any modification! All I had to do was enable 'OTG storage' in my phone's settings (without this option enabled the audio interface would not get any power from the phone).
