### ISSUE TITLE
using pretrained model with pitch

### ISSUE THREAD

**Issue by zhouyong64** [alphacep/vosk-android-demo#120]
I have a pretrained model with pitch input. Using this model in vosk will result in feature dimension mismatch error. I understand vosk advocates against using pitch. Is it possible to adapt this model to use with vosk?

**Comment by nshmyrev** [comment]
You have to modify the code, you can do something like this:

```
    pitch_conf_rxfilename_ = model_path_str_ + "/conf/pitch.conf";

    if (stat(pitch_conf_rxfilename_.c_str(), &buffer) == 0) {
        KALDI_LOG << "Using pitch in feature pipeline";
        feature_info_.add_pitch = true;
        ReadConfigFromFile(pitch_conf_rxfilename_, &feature_info_.pitch_opts);
    }

```

**Comment by zhouyong64** [comment]
Thanks. Solved the problem with your code.

**Comment by nshmyrev** [comment]
It seems to work, let me know if other issues exist please.
