### ISSUE TITLE
Crash with 12000 Hz rate 

### ISSUE THREAD

**Issue by marlon-br** [alphacep/vosk-android-demo#125]
Hi, accidentally I was trying an audio from slow-motion video and found one strange crash:

1. Audio is 12000 Hz
2. If I use small Russian model no crashes (actually no speech recognized, but the audio does not contain any speech)
3. If I use small English (or German) it crashes and logcat has: 

```
E/VoskAPI: MaybeCreateResampler():online-feature.cc:99) Sampling frequency mismatch, expected 16000, got 12000
    Perhaps you want to use the options --allow_{upsample,downsample}
E/libc++abi: terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 29975 (pool-8-thread-1), pid 29629  
``` 

It happens while the first `rec.AcceptWaveform(arr, buffer_size);` call and recognizer is initialized with 12000 Hz

**Comment by nshmyrev** [comment]
This is expected, you can not decode 12khz audio with wideband model. You need narrowband model.

You can add --allow-upsample=true to model/mfcc.conf, it will decode, but the accuracy will not be great.

**Comment by marlon-br** [comment]
ok, thank you for the clarification
