### ISSUE TITLE
Improve accuracy for hot word detection

### ISSUE THREAD

**Issue by dewijones92** [alphacep/vosk-android-demo#127]
https://photos.app.goo.gl/M34ZXSNToWKnmiAH6

Hi
I am trying to make a hot word detection app that listens for the phrase "care direct". 
I am using the tip of master 1725bde253128641e544471f875cf736474ee0a1
Here is the only code change:
`rec = new KaldiRecognizer(activityReference.get().model, 16000.f, "[\"care direct\"]");`

As you can see from the video the accuracy is pretty poor - despite stating the phrase in the grammar argument.
Any tips to improve accuracy? 
many thanks :-)

**Comment by nshmyrev** [comment]
Vosk doesn't support keyword spotting yet. To track the progress you can subscribe to

https://github.com/alphacep/vosk-api/issues/107

**Comment by nshmyrev** [comment]
@dewijones92 and, from the video it doesn't seem your change applied in the app, it still recognizes big vocabulary. Probably you didn't update the apk propery. You also need to add [unk] word for the rest.

**Comment by dewijones92** [comment]
Sorry, please forget I mentioned "hot word" detection. I just happen to be solely interested in one phrase  ;)
How can I improve the accuracy? Have I specified the grammar argument correctly? Use a different model?  
Any help would be greatly appreciated :)

**Comment by nshmyrev** [comment]
> Have I specified the grammar argument correctly?

You should have modified this line:

https://github.com/alphacep/vosk-android-demo/blob/1725bde253128641e544471f875cf736474ee0a1/app/src/main/java/org/kaldi/demo/KaldiActivity.java#L274

not the line above. The line above which you modified is for file recognition.

**Comment by dewijones92** [comment]
I love you

**Comment by nshmyrev** [comment]
You are welcome

**Comment by dewijones92** [comment]
btw
It works perfectly now. I'd say vosk fully supports keyword spotting. Or am I missing something?

**Comment by nshmyrev** [comment]
> It works perfectly now. I'd say vosk fully supports keyword spotting. Or am I missing something?

It should drain battery a bit and generate false alarms, but you can test of course.

**Comment by dewijones92** [comment]
From my testing it doesn't generate any false positives or negatives. Works perfectly.

**Comment by dewijones92** [comment]
@nshmyrev  It does generate some false positives actually. How would I reduce false positives? I feel like I am nearly there with it. Which model do you recommend? Many thanks.

**Comment by Dominapp** [comment]
I have the same problem great results but lots of false positive.
@nshmyrev Please any idea?

**Comment by dewijones92** [comment]
@Dominapp i have really good results now. Maybe i can help?

**Comment by Dominapp** [comment]
Sure, Thanks!
How did you reduce the false positive? 
Can you share your code please?

**Comment by dewijones92** [comment]
@Dominapp 

the following code is heavily based on the code in this repo
```
KaldiRecognizer rec = new KaldiRecognizer(this.model, 16000.f, "[\"hot word\", \"[unk]\"]");
voskSpeechService = new SpeechService(rec, 16000.0f);
```

```
  public void onResult(final String hypothesis) {
    Gson gson = new Gson();
    Result voiceResult = gson.fromJson(hypothesis, Result.class);

    if (voiceResult.text.toLowerCase().equals("hot word")) {
      for(Result result : voiceResult.result){
        if(result.conf < 0.9) return;
      }
      Log.d(LOG_TAG, ">>>> VOICE ACTIVATED: " + result.text);
    }

  }
```

also...
Vosk dies after a certain amount of time so I check the last time Vosk returned a result in either onResult or onPartialResult and restart if no result in more than 5 seconds

Vosk sometimes errors on startup so I then wait 1 second before starting vosk again

I hope this helps?
