### ISSUE TITLE
Why is nothing detected when I first speak 

### ISSUE THREAD

**Issue by dewijones92** [alphacep/vosk-android-demo#128]
https://photos.app.goo.gl/M34ZXSNToWKnmiAH6

Hi
I am using the tip of master 1725bde
Here is the only code change:
rec = new KaldiRecognizer(activityReference.get().model, 16000.f, "[\"care direct\"]");

Why is nothing detected when I first speak? It works from the second sentence onwards. 
many thanks :-)

**Comment by nshmyrev** [comment]
There is no need to open the same issue as #127, you can just edit the title
