### ISSUE TITLE
Result in Editor

### ISSUE THREAD

**Issue by niebert** [alphacep/vosk-android-demo#131]
What is the best (recommended) way to modify the demo app so that the recognized sequence of words are stored in textarea or textbox, that can be saved to the SD card?

**Comment by nshmyrev** [comment]
What is the problem exactly? The code like this should work:

https://stackoverflow.com/questions/24059022/android-write-text-in-file-sd-card

**Comment by niebert** [comment]
Thank you very much,

**Comment by nshmyrev** [comment]
Ok, feel free to close the issue or open new one if you have other questions.

**Comment by niebert** [comment]
According to a process chain I though about a prototype installable via F-Droid and connect OpenSource apps to that it works like Abstraction Layer for a Speech Recognition interface. Th   user would be able to select to which offline speech recognition is plugged into the SR abstraction layer. That is similar to a [Database Abstraction Layer](https://en.wikipedia.org/wiki/Database_abstraction_layer). Do not know if that makes sense or if I have to dig deep into the code to get that right? best regards,

**Comment by nshmyrev** [comment]
@niebert sure, if someone can implement a layer it would be great, see previous discussion here:

#126

**Comment by niebert** [comment]
Does that need a kind of negotiation between the Open Source Offline SR implementation so that the abstraction layer serves the requirements and constraints of those projects or application driven, will think about it. best regards, Bert
