### ISSUE TITLE
在Gradle编译的时候报错误

### ISSUE THREAD

**Issue by Re-bin** [alphacep/vosk-android-demo#135]
下载的是2021年4月份最新的release版本Gradle编译不通过
![image](https://user-images.githubusercontent.com/52506698/115210344-12741900-a131-11eb-9330-4bf4feeef6c7.png)

**Comment by nshmyrev** [comment]
I'm sorry, this is a standard library. Seems like an issue with your netowrk or with android cache. Maybe gradle cache cleanup will help.
