### ISSUE TITLE
memory leakage on Android?

### ISSUE THREAD

**Issue by zli18** [alphacep/vosk-android-demo#14]
Hi, I am testing this demo on Samsung S7 and S8. When I profile the app, I found the memory usage keeps increasing, for both microphone or file recognition. It seems to have memory leakage in the recognizer. Do you have a chance to take a look? Thanks a lot.

**Comment by nshmyrev** [comment]
Ok, I'll check. Please provide the numbers, what memory size do you see in what period of time. Thanks

**Comment by zli18** [comment]
Tested on S7 with Android 7.0, every time I click "recognize file" the memory usage increase around 40MB. Occasionally when the memory reaches ~500mb, it drops to below 200mb, but other time, it just keeps increasing. Microphone got the similar behavior. Also tested on S8 with Android 9.0, same results. Thanks.

**Comment by nshmyrev** [comment]
This should be fixed now with https://github.com/alphacep/vosk-api/issues/83
