### ISSUE TITLE
Cannot open config file "mfcc.conf"

### ISSUE THREAD

**Issue by Moufdi96** [alphacep/vosk-android-demo#142]
Hello, I am trying to integrate a french model in my android App. With the lightweight model the "vosk-model-small-fr-pguyot-0.3"  it worked just fine, but I want to try the 280 MB model "fr-pguyot-zamia-20191016-tdnn_f"  for more accuracy  and I'm getting this error. I would be grateful for any help.

VoskAPI: ReadConfigFile():parse-options.cc:462) Cannot open config file: /storage/emulated/0/Android/data/com.example.myapplication/files/model/model-fr-france2/mfcc.conf
E/libc++abi: terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 15959 (pool-2-thread-1), pid 15903 (e.myapplication)

**Comment by nshmyrev** [comment]
It says file is missing, probably it was not unpacked. You can check earlier logcat logs for details how files are copied to sdcard.

**Comment by Moufdi96** [comment]
> It says file is missing, probably it was not unpacked. You can check earlier logcat logs for details how files are copied to sdcard.

Thank you for your answer, I had cases where some models were not properly unpacked and an exception was thrown with a Toast message saying "unpacking model failed", but there is no such exception this time !!

**Comment by Moufdi96** [comment]
> > It says file is missing, probably it was not unpacked. You can check earlier logcat logs for details how files are copied to sdcard.
> 
> Thank you for your answer, I had cases where some models were not properly unpacked and an exception was thrown with a Toast message saying "unpacking model failed", but there is no such exception this time !!

**Comment by Moufdi96** [comment]
> > It says file is missing, probably it was not unpacked. You can check earlier logcat logs for details how files are copied to sdcard.
> 
> Thank you for your answer, I had cases where some models were not properly unpacked and an exception was thrown with a Toast message saying "unpacking model failed", but there is no such exception this time !!

This issue is solve, you were right there has been some files path issues.
But now I've got a new problem !! any hints to solve this please ?

2021-05-17 11:21:07.157 11768-11768/com.example.myapplication D/UnpackingModel: Success
2021-05-17 11:21:07.158 11768-11768/com.example.myapplication E/VoskAPI: DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:46) Input feature dimension mismatch: got 13 but network expects 40
2021-05-17 11:21:07.172 11768-11768/com.example.myapplication E/libc++abi: terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError
2021-05-17 11:21:07.172 11768-11768/com.example.myapplication A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 11768 (e.myapplication), pid 11768 (e.myapplication)

**Comment by nshmyrev** [comment]
> 2021-05-17 11:21:07.158 11768-11768/com.example.myapplication E/VoskAPI: DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:46) Input feature dimension mismatch: got 13 but network expects 40

mfcc.conf doesn't match final.mdl, you should be using hires version probably.

**Comment by nshmyrev** [comment]
> but I want to try the 280 MB model "fr-pguyot-zamia-20191016-tdnn_f" for more accuracy

zamia model is bigger but less accurate actually.

**Comment by Moufdi96** [comment]
> > but I want to try the 280 MB model "fr-pguyot-zamia-20191016-tdnn_f" for more accuracy
> 
> zamia model is bigger but less accurate actually.

Okay thank you so much for your feedback.
