### ISSUE TITLE
gradle url error...

### ISSUE THREAD

**Issue by jysim1** [alphacep/vosk-android-demo#149]
===err log====
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.alphacephei:vosk:0.3.28.
     Required by:
         project :app
      > Could not resolve com.alphacephei:vosk:0.3.28.
         > Could not get resource 'https://alphacephei.com/maven/com/alphacephei/vosk/0.3.28/vosk-0.3.28.pom'.
            > Could not GET 'https://alphacephei.com/maven/com/alphacephei/vosk/0.3.28/vosk-0.3.28.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.0.1/userguide/build_environment.html#gradle_system_properties
                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by nshmyrev** [comment]
The message tells you what to do:

> The server may not support the client's requested TLS protocol versions: (TLSv1.2). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.0.1/userguide/build_environment.html#gradle_system_properties
