### ISSUE TITLE
SSL certificate of alphacephei.com expired

### ISSUE THREAD

**Issue by abouquet** [alphacep/vosk-android-demo#154]
![image](https://user-images.githubusercontent.com/2518542/128175376-aef51085-5836-482e-ab6b-1f4f030d3961.png)

It prevents Maven or Gradle to download dependency

```
      > Could not resolve com.alphacephei:vosk-android:0.3.23.
         > Could not get resource 'https://alphacephei.com/maven/com/alphacephei/vosk-android/0.3.23/vosk-android-0.3.23.pom'.
            > Could not GET 'https://alphacephei.com/maven/com/alphacephei/vosk-android/0.3.23/vosk-android-0.3.23.pom'.
               > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```

**Comment by abouquet** [comment]
Following this ticket to prevent further downloading issue. Any plan to put this dependency on mavenCentral ?

**Comment by nshmyrev** [comment]
We don't plan to put things on maven central, their upload process is not quite clear for me.

Certificate is update now, thanks for report!
