### ISSUE TITLE
add vosk-android-demo apk to fdroid.org

### ISSUE THREAD

**Issue by freddii** [alphacep/vosk-android-demo#159]
It would be nice to have vosk-android-demo at https://www.f-droid.org

**Comment by nshmyrev** [comment]
It is tracked here:

https://github.com/alphacep/vosk-api/issues/558

the main issue we need to put our jars to public repo

**Comment by TechnologyClassroom** [comment]
The issue that was a blocker is closed.  Does this mean vosk-android-demo is now clear for F-Droid?

**Comment by nshmyrev** [comment]
It is kind of a demo, no much point to have it on Android actually. We have another app with a virtual keyboard

https://github.com/alphacep/vosk-android-service

That one we plan to submit to F-droid when it is ready. A bit far from ready yet though.

**Comment by nshmyrev** [comment]
And, dicio assistant using Vosk is on f-droid already I believe.
