### ISSUE TITLE
Using custom model tdnn_lstm in vosk?

### ISSUE THREAD

**Issue by mlexplore1122** [alphacep/vosk-android-demo#177]
Hi,
I already have model training with nnet3 tdnn_lstm and output model in server has structure like this image:
![image](https://user-images.githubusercontent.com/68678036/154048512-9120e865-b032-4068-a3ff-876658184f39.png)
And I try to replace folder: "model-en-us" in assess with my model's file like this image:
![image](https://user-images.githubusercontent.com/68678036/154048753-ad4b513c-2744-4327-a8d1-47ac2f9ebe97.png)
But when runing it failed:
![image](https://user-images.githubusercontent.com/68678036/154048851-2bf923a5-fd1e-4535-96ac-9427b55a25c9.png)
So I wonder, Does vosk support tdnn_lstm, if not, what's wrong with my setup to run own model.
Thank you

**Comment by nshmyrev** [comment]
You don't have `conf/model.conf` in your model. It is mandatory. You need to create that file. You can copy from another model.

**Comment by mlexplore1122** [comment]
tks @nshmyrev 
I have add conf/model.conf from another model. But With my model, I just not using only mfcc, it's also using pitch for feature. So I have  file online.conf:
![image](https://user-images.githubusercontent.com/68678036/154422552-eced525f-6040-4d51-ad28-599aacae9026.png)
and file online_cmvn.conf:
![image](https://user-images.githubusercontent.com/68678036/154422640-667072d5-14e6-485c-8bdf-02bd35f799c0.png)
and the last is file online_pitch.conf
![image](https://user-images.githubusercontent.com/68678036/154422746-b3f64cd7-2fb4-418d-8c79-d8653e9645d0.png)
I don't know how to copy all conf to file model.conf or need do something for it;'s work. In case I do nothing, Model will failed when running because it's not understand iput is dimension with 40 of mfcc, and 4 of pitch.
Thanks

**Comment by nshmyrev** [comment]
You need to create conf/pitch.conf then as described in https://alphacephei.com/vosk/models#model-structure

**Comment by mlexplore1122** [comment]
tks you. I will try it.

**Comment by mlexplore1122** [comment]
My pitch cofig has same like this.
https://github.com/kaldi-asr/kaldi/blob/master/egs/csj/s5/conf/online_pitch.conf
And I try move this config to file conf/pitch.conf
![image](https://user-images.githubusercontent.com/68678036/154426132-530f1332-98d3-4301-89fa-eff16a191152.png)
But it does'nt understand all option in pitch.conf
![image](https://user-images.githubusercontent.com/68678036/154426238-50bf1fee-134c-4d4c-979c-88ae6356a874.png)
Can you check it. Tks

**Comment by nshmyrev** [comment]
Leave just --add-raw-log-pitch and probably the delay

**Comment by mlexplore1122** [comment]
I try to remove each option in list, but the important option is --add-raw-log-pitch=true failed,
It's show Invalid option --add-raw-log-pitch=true in config file. 
If I remove this option, it not show error, but when running, error running show the input feature has dimension is 43, but model expectation 44. So Still can't run this. :(

**Comment by nshmyrev** [comment]
Ok, so I've just pushed this fix  https://github.com/alphacep/vosk-api/commit/ad546a8f1a915ee166407e8d82c8cd2cc9cb8ec0 which should help you. But you need to rebuild the library yourself.

**Comment by trangtv57** [comment]
tks @nshmyrev, I will try new fix then report later. Tks

**Comment by mlexplore1122** [comment]
ok, It's work, tks @nshmyrev very much
