### ISSUE TITLE
Support version android

### ISSUE THREAD

**Issue by trucvip123** [alphacep/vosk-android-demo#179]
Thanks for your demo. 
Vosk support for android 10 yet? Please!

Thank you^^

**Comment by nshmyrev** [comment]
> Vosk support for android 10 yet? Please!

Yes I think it should work

**Comment by trucvip123** [comment]
Thanks so much.

How to convert model after training to model support for android?

Xie xie ^^

**Comment by nshmyrev** [comment]
You already asked the same question here:

https://github.com/alphacep/vosk-api/issues/899

**Comment by trucvip123** [comment]
After the training is complete, the model can be used for mobile or need a tool to convert to mobile form?

**Comment by nshmyrev** [comment]
There is no converter, you just arrange the files

**Comment by nshmyrev** [comment]
You can continue in other issue
