### ISSUE TITLE
Implement SpeechService as a android.speech.RecognitionService

### ISSUE THREAD

**Issue by abouquet** [alphacep/vosk-android-demo#192]
As the title say. The better we can use existing Android abstraction of SpeechService, the easier Vosk Android will be adopted.

I'm on the way to integrate it and start VoskService with this way

```
  val recognizer = SpeechRecognizer.createSpeechRecognizer(context, VOSK_SERVICE_COMPONENT)
```

All we have to to is to make `SpeechService` extends `android.speech.RecognitionService` and Android api will take care of the Service management (bind / unbind / start / stop etc...)

There is also a layer adpatation to convert recognition events to match `android.speech.RecognitionListener`

**Comment by nshmyrev** [comment]
Thank you for your request. We have https://github.com/alphacep/vosk-android-service project for that.

**Comment by abouquet** [comment]
Oh, nice ! I didn't see it ! 
I've got now my own implementation of `android.speech.RecognitionService` backed by Vosk. I think I'm gonna give it a try with your solution :)
