### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Sonia-Mood** [alphacep/vosk-android-demo#206]
Hi,
I've integrated Kaldifatal error  in a macos  I get the following crash dump

python3 main.py
x exp/
x exp/chain_cleaned/
x exp/chain_cleaned/tdnn_1d_sp/
x exp/chain_cleaned/tdnn_1d_sp/phones.txt
x exp/chain_cleaned/tdnn_1d_sp/num_jobs
x exp/chain_cleaned/tdnn_1d_sp/phone_lm.fst
x exp/chain_cleaned/tdnn_1d_sp/tree
x exp/chain_cleaned/tdnn_1d_sp/0.trans_mdl
x exp/chain_cleaned/tdnn_1d_sp/den.fst
x exp/chain_cleaned/tdnn_1d_sp/normalization.fst
x exp/chain_cleaned/tdnn_1d_sp/cmvn_opts
x exp/chain_cleaned/tdnn_1d_sp/final.ie.id
x exp/chain_cleaned/tdnn_1d_sp/lda.mat
x exp/chain_cleaned/tdnn_1d_sp/srand
x exp/chain_cleaned/tdnn_1d_sp/accuracy.report
x exp/chain_cleaned/tdnn_1d_sp/configs/
x exp/chain_cleaned/tdnn_1d_sp/configs/network.xconfig
x exp/chain_cleaned/tdnn_1d_sp/configs/xconfig
x exp/chain_cleaned/tdnn_1d_sp/configs/xconfig.expanded.1
x exp/chain_cleaned/tdnn_1d_sp/configs/xconfig.expanded.2
x exp/chain_cleaned/tdnn_1d_sp/configs/init.config
x exp/chain_cleaned/tdnn_1d_sp/configs/ref.config
x exp/chain_cleaned/tdnn_1d_sp/configs/final.config
x exp/chain_cleaned/tdnn_1d_sp/configs/init.raw
x exp/chain_cleaned/tdnn_1d_sp/configs/ref.raw
x exp/chain_cleaned/tdnn_1d_sp/configs/vars
x exp/chain_cleaned/tdnn_1d_sp/configs/lda.mat
x exp/chain_cleaned/tdnn_1d_sp/0.mdl
x exp/chain_cleaned/tdnn_1d_sp/final.mdl
x exp/chain_cleaned/tdnn_1d_sp/frame_subsampling_factor
x exp/
x exp/nnet3_cleaned/
x exp/nnet3_cleaned/extractor/
x exp/nnet3_cleaned/extractor/final.dubm
x exp/nnet3_cleaned/extractor/final.mat
x exp/nnet3_cleaned/extractor/global_cmvn.stats
x exp/nnet3_cleaned/extractor/splice_opts
x exp/nnet3_cleaned/extractor/online_cmvn.conf
x exp/nnet3_cleaned/extractor/num_jobs
x exp/nnet3_cleaned/extractor/final.ie
x exp/nnet3_cleaned/extractor/final.ie.id
x exp/nnet3_cleaned/extractor/10.ie
x data/
x data/lang_test_tgsmall/
x data/lang_test_tgsmall/L.fst
x data/lang_test_tgsmall/L_disambig.fst
x data/lang_test_tgsmall/oov.int
x data/lang_test_tgsmall/oov.txt
x data/lang_test_tgsmall/phones.txt
x data/lang_test_tgsmall/topo
x data/lang_test_tgsmall/words.txt
x data/lang_test_tgsmall/G.fst
x data/lang_test_tgsmall/phones/
x data/lang_test_tgsmall/phones/sets.txt
x data/lang_test_tgsmall/phones/roots.txt
x data/lang_test_tgsmall/phones/silence.txt
x data/lang_test_tgsmall/phones/nonsilence.txt
x data/lang_test_tgsmall/phones/optional_silence.txt
x data/lang_test_tgsmall/phones/context_indep.txt
x data/lang_test_tgsmall/phones/extra_questions.txt
x data/lang_test_tgsmall/phones/disambig.txt
x data/lang_test_tgsmall/phones/word_boundary.txt
x data/lang_test_tgsmall/phones/align_lexicon.txt
x data/lang_test_tgsmall/phones/align_lexicon.int
x data/lang_test_tgsmall/phones/wdisambig.txt
x data/lang_test_tgsmall/phones/wdisambig_phones.int
x data/lang_test_tgsmall/phones/wdisambig_words.int
x data/lang_test_tgsmall/phones/silence.int
x data/lang_test_tgsmall/phones/silence.csl
x data/lang_test_tgsmall/phones/nonsilence.int
x data/lang_test_tgsmall/phones/nonsilence.csl
x data/lang_test_tgsmall/phones/optional_silence.int
x data/lang_test_tgsmall/phones/optional_silence.csl
x data/lang_test_tgsmall/phones/disambig.int
x data/lang_test_tgsmall/phones/disambig.csl
x data/lang_test_tgsmall/phones/context_indep.int
x data/lang_test_tgsmall/phones/context_indep.csl
x data/lang_test_tgsmall/phones/sets.int
x data/lang_test_tgsmall/phones/extra_questions.int
x data/lang_test_tgsmall/phones/roots.int
x data/lang_test_tgsmall/phones/word_boundary.int
x exp/
x exp/rnnlm_lstm_1a/
x exp/rnnlm_lstm_1a/config/
x exp/rnnlm_lstm_1a/config/words.txt
x exp/rnnlm_lstm_1a/config/oov.txt
x exp/rnnlm_lstm_1a/config/data_weights.txt
x exp/rnnlm_lstm_1a/config/unigram_probs.txt
x exp/rnnlm_lstm_1a/config/features.txt
x exp/rnnlm_lstm_1a/config/xconfig
x exp/rnnlm_lstm_1a/config/nnet/
x exp/rnnlm_lstm_1a/config/nnet/xconfig
x exp/rnnlm_lstm_1a/config/nnet/xconfig.expanded.1
x exp/rnnlm_lstm_1a/config/nnet/xconfig.expanded.2
x exp/rnnlm_lstm_1a/config/nnet/ref.config
x exp/rnnlm_lstm_1a/config/nnet/final.config
x exp/rnnlm_lstm_1a/config/nnet/ref.raw
x exp/rnnlm_lstm_1a/config/nnet/vars
x exp/rnnlm_lstm_1a/feat_embedding.final.mat
x exp/rnnlm_lstm_1a/final.raw
x exp/rnnlm_lstm_1a/info.txt
x exp/rnnlm_lstm_1a/word_feats.txt
x exp/rnnlm_lstm_1a/special_symbol_opts.txt
tree-info exp/chain_cleaned/tdnn_1d_sp/tree 
tree-info exp/chain_cleaned/tdnn_1d_sp/tree 
fstpushspecial 
fstminimizeencoded 
fstdeterminizestar --use-log=true 
fsttablecompose data/lang_test_tgsmall/L_disambig.fst data/lang_test_tgsmall/G.fst 
fstisstochastic data/lang_test_tgsmall/tmp/LG.fst 
fstcomposecontext --context-size=2 --central-position=1 --read-disambig-syms=data/lang_test_tgsmall/phones/disambig.int --write-disambig-syms=data/lang_test_tgsmall/tmp/disambig_ilabels_2_1.int data/lang_test_tgsmall/tmp/ilabels_2_1.53441 data/lang_test_tgsmall/tmp/LG.fst 
fstisstochastic data/lang_test_tgsmall/tmp/CLG_2_1.fst 
make-h-transducer --disambig-syms-out=exp/chain_cleaned/tdnn_1d_sp/graph_tgsmall/disambig_tid.int --transition-scale=1.0 data/lang_test_tgsmall/tmp/ilabels_2_1 exp/chain_cleaned/tdnn_1d_sp/tree exp/chain_cleaned/tdnn_1d_sp/final.mdl 
fsttablecompose exp/chain_cleaned/tdnn_1d_sp/graph_tgsmall/Ha.fst 'fstrmsymbols --remove-arcs=true --apply-to-output=true data/lang_test_tgsmall/oov.int data/lang_test_tgsmall/tmp/CLG_2_1.fst|' 
fstminimizeencoded 
fstdeterminizestar --use-log=true 
fstrmsymbols exp/chain_cleaned/tdnn_1d_sp/graph_tgsmall/disambig_tid.int 
fstrmepslocal 
fstrmsymbols --remove-arcs=true --apply-to-output=true data/lang_test_tgsmall/oov.int data/lang_test_tgsmall/tmp/CLG_2_1.fst 
fstisstochastic exp/chain_cleaned/tdnn_1d_sp/graph_tgsmall/HCLGa.fst 
add-self-loops --self-loop-scale=1.0 --reorder=true exp/chain_cleaned/tdnn_1d_sp/final.mdl exp/chain_cleaned/tdnn_1d_sp/graph_tgsmall/HCLGa.fst 
fstisstochastic exp/chain_cleaned/tdnn_1d_sp/graph_tgsmall/HCLG.fst 
../../../src/latbin/lattice-best-path 'ark:gunzip -c exp/chain_cleaned/tdnn_1d_sp/decode_test_tgsmall/lat.1.gz |' 'ark,t:| utils/int2sym.pl -f 2- /Users/nehruboda/kaldi/egs/kaldi-asr-tutorial/s5/exp/chain_cleaned/tdnn_1d_sp/graph_tgsmall/words.txt > out.txt' 
LOG (lattice-best-path[5.5.1074~1-71f3]:main():lattice-best-path.cc:99) For utterance gettysburg, best cost 413.925 + -15118.7 = -14704.8 over 334 frames.
LOG (lattice-best-path[5.5.1074~1-71f3]:main():lattice-best-path.cc:124) Overall cost per frame is -44.0263 = 1.2393 [graph] + -45.2656 [acoustic] over 334 frames.
LOG (lattice-best-path[5.5.1074~1-71f3]:main():lattice-best-path.cc:128) Done 1 lattices, failed for 0
head: illegal line count -- -1
cmp: EOF on -
../../../src/latbin/lattice-best-path 'ark:gunzip -c exp/chain_cleaned/tdnn_1d_sp/decode_test_rescore/lat.1.gz |' 'ark,t:| utils/int2sym.pl -f 2- /Users/nehruboda/kaldi/egs/kaldi-asr-tutorial/s5/exp/chain_cleaned/tdnn_1d_sp/graph_tgsmall/words.txt > out_rescore.txt' 
gunzip: can't stat: exp/chain_cleaned/tdnn_1d_sp/decode_test_rescore/lat.1.gz (exp/chain_cleaned/tdnn_1d_sp/decode_test_rescore/lat.1.gz.gz): No such file or directory
LOG (lattice-best-path[5.5.1074~1-71f3]:main():lattice-best-path.cc:124) Overall cost per frame is nan = nan [graph] + nan [acoustic] over 0 frames.
LOG (lattice-best-path[5.5.1074~1-71f3]:main():lattice-best-path.cc:128) Done 0 lattices, failed for 0
WARNING (lattice-best-path[5.5.1074~1-71f3]:Close():kaldi-io.cc:515) Pipe gunzip -c exp/chain_cleaned/tdnn_1d_sp/decode_test_rescore/lat.1.gz | had nonzero return status 256
ERROR (lattice-best-path[5.5.1074~1-71f3]:~SequentialTableReaderArchiveImpl():util/kaldi-table-inl.h:678) TableReader: error detected closing archive 'gunzip -c exp/chain_cleaned/tdnn_1d_sp/decode_test_rescore/lat.1.gz |'

[ Stack-Trace: ]
0   lattice-best-path                   0x0000000100d915d0 kaldi::KaldiGetStackTrace() + 64
1   lattice-best-path                   0x0000000100d9142c kaldi::MessageLogger::LogMessage() const + 312
2   lattice-best-path                   0x0000000100cab1e0 kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&) + 32
3   lattice-best-path                   0x0000000100cbf1fc kaldi::SequentialTableReaderArchiveImpl<kaldi::CompactLatticeHolder>::~SequentialTableReaderArchiveImpl() + 224
4   lattice-best-path                   0x0000000100cbec40 kaldi::SequentialTableReaderArchiveImpl<kaldi::CompactLatticeHolder>::~SequentialTableReaderArchiveImpl() + 12
5   lattice-best-path                   0x0000000100cbec54 kaldi::SequentialTableReaderArchiveImpl<kaldi::CompactLatticeHolder>::~SequentialTableReaderArchiveImpl() + 12
6   lattice-best-path                   0x0000000100cc16fc kaldi::SequentialTableReader<kaldi::CompactLatticeHolder>::~SequentialTableReader() + 36
7   lattice-best-path                   0x0000000100cac128 kaldi::SequentialTableReader<kaldi::CompactLatticeHolder>::~SequentialTableReader() + 12
8   lattice-best-path                   0x0000000100caabf0 main + 1928
9   dyld                                0x000000010124d0f4 start + 520

libc++abi: terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError
could you rectify these error

_Originally posted by @Sonia-Mood in https://github.com/alphacep/vosk-android-demo/issues/45#issuecomment-1666533850_

**Comment by nshmyrev** [comment]
Not sure how is this related to vosk-android-demo. Please stop spamming
