### ISSUE TITLE
Cannot create a model with vosk-model-small-pt-0.3

### ISSUE THREAD

**Issue by SchweitzerGAO** [alphacep/vosk-android-demo#207]
I think this is because the files are not correctly organized to different directories like other models do. BTW there is no "model.conf" in the zip file. could you please tell me how to download it?
![image](https://github.com/alphacep/vosk-android-demo/assets/64410968/7b9176a6-fcad-443d-aa58-31ae5eeed19c)

**Comment by nshmyrev** [comment]
This is so-called V1 model structure, it should also work. What doesn't work for you exactly?

You can arrange files in V2 structure and pick model.conf from other small model.

**Comment by SchweitzerGAO** [comment]
> 

Thx! I did exactly what you suggested and it worked properly.
