### ISSUE TITLE
When vosk is used on Android, does it support hardware acceleration?

### ISSUE THREAD

**Issue by xubinlu** [alphacep/vosk-android-demo#215]
When using vosk on a tablet, recognition is slow and the results are inaccurate. 
Is hardware acceleration supported when using on android? 
Are there any other ways to improve recognition speed?

**Comment by nshmyrev** [comment]
> Is hardware acceleration supported when using on android?

No

> Are there any other ways to improve recognition speed?

What model do you use?

**Comment by xubinlu** [comment]
I use vosk-model-small-cn-0.22

**Comment by nshmyrev** [comment]
Try Sherpa https://k2-fsa.github.io/sherpa/onnx/android/index.html

**Comment by xubinlu** [comment]
Thank you
