### ISSUE TITLE
Japanese Model

### ISSUE THREAD

**Issue by cuongttn2** [alphacep/vosk-android-demo#226]
Hello everyone, 
I have some questions about vosk-model-small-ja-0.22 and vosk-model-ja-0.22, Is vosk-model-ja-0.22 enough for a japanese speech recognition app on Android ?. 
Is there any way to handle the Japanese Model (1GB - https://alphacephei.com/vosk/models/vosk-model-ja-0.22.zip) having large file size? When I import it into the models module, it always gives an error (java.lang.OutOfMemoryError: Java heap space).

**Comment by nshmyrev** [comment]
You can remove rescore  folder from large Japanese model, it might fit your phone.  You can also try SenseVoice, it is much more accurate.

**Comment by cuongttn2** [comment]
> You can remove rescore folder from large Japanese model, it might fit your phone. You can also try SenseVoice, it is much more accurate.

Thank you very much
