### ISSUE TITLE
Possible feature to get phones or do n-gram search / classification

### ISSUE THREAD

**Issue by nckshr** [alphacep/vosk-android-demo#41]
Hi there,

I am super new to speech recognition (apologies for ignorance) but found this great repo and am wondering if it would be difficult to expand the API to allow for retrieval of phoneme matches or n-gram recognition instead of macthing against the entire dictionary? I am trying to create an application that listens for specific keywords / grammar structure and would be able to get much greater accuracy if the recognizer could limit possible recognitions to a more limited set of words / phrases. At the very least it might be nice to get the recognized phonemes so I could compare them to phoneme priors for the set of words I want to listen for. Would I need to create my own model for that? I was hoping they might already be available from the recognizer somehow. My apologies if this already exists and I just missed the appropriate docs.

**Comment by nshmyrev** [comment]
You can create KaldiRecognizer from word list here:

                rec = new KaldiRecognizer(activityReference.get().model, 16000.f);

like this:

                rec = new KaldiRecognizer(activityReference.get().model, 16000.f, "one two three four five");

See also https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py

**Comment by nckshr** [comment]
Oh awesome, thanks! I'll definitely give that a try. Just in case I missed it, is there a wiki or docs somewhere that you would recommend I use when exploring the API? Maybe I could answer my own stupid questions before bugging you about it

**Comment by nshmyrev** [comment]
We do not have docs yet.

**Comment by nckshr** [comment]
hmm, this seems to be an option for python, but I'm not seeing a corresponding constructor for android? I get an error when trying to put a word list at the end:

`KaldiRecognizer recognizer = new KaldiRecognizer(model,16000.f, "one two three");`

in the  KaldiRecognizer.class file, I only see this constructor:

` public KaldiRecognizer(Model model, float sample_frequency) {
        this(voskJNI.new_KaldiRecognizer(Model.getCPtr(model), model, sample_frequency), true);
    }
`
any plans to integrate word lists into the android project? It would also be great to be able to register key phrases, as this would give the model stronger priors for what phonemes to expect next

**Comment by nshmyrev** [comment]
Hi!

I have just pushed aar update, please pull and try again.

**Comment by nckshr** [comment]
Great, thanks! I'll give it a try. Concerning the word list, is this something like a keyword search where the task is classification, rather than arbitrary text recognition with confidence thresholds? I am wanting to increase accuracy by limiting to a predefined set of words, but I also want to be able to recognize if none of the presets are being detected (to prevent false positives). I don't know much about speech recognition specifically, but I do come from the ML / AI side of things, so I could see how it would be difficult to do this using a classification task as there's no notion of individual phrase confidence (only which is closest). Let me know if you think there's a better way to accomplish my goal, any advice is much appreciated!

**Comment by nshmyrev** [comment]
You can not do this right now. You can track https://github.com/alphacep/vosk-api/issues/55 for the updates.

**Comment by nshmyrev** [comment]
Lets track it at https://github.com/alphacep/vosk-api/issues/55
