### ISSUE TITLE
Is it possible to implement pause method in order to release the recorder ? 

### ISSUE THREAD

**Issue by abouquet** [alphacep/vosk-android-demo#48]
Hi,

I would like a `pause()` method in order to be able to launch quicker again without analyzing and integrating the `model` object again.
Is it possible to do that ?

It seems that when I'm trying to `stop()` and `start()` the recognizer, native layer is crashing. Maybe because Ican't use any reference asap I've called `stop()` on the recognizer.

Regards

**Comment by nshmyrev** [comment]
I'm sorry, I don't quite get your problem. Just create a new KaldiRecognizer, it is fast.

**Comment by abouquet** [comment]
I've got a multi implemention of recognition engine (sphinx and kaldi) and I would like to swap from one to an other between 2 utterances. It seems to be not as fast as it should (at least in debug mode)

**Comment by nshmyrev** [comment]
Ok, you'd better provide me more details on what is slow exactly. And why do you need sphinx.

**Comment by abouquet** [comment]
It's slow like 1-3 seconds when I instantiate the engine at each start (it's maybe related to jni loading I have to do more tests about the start issue)

I need sphinx as it can process keyworld spotting mode and allow swapping to multiple dictionnaries (based on keyword list file) quickly (just have to declare phonems and word in a file and linkt it to a kw list file) but I had difficulties when it comes to numbers recognitions...

Kaldi is based on native language, better for number based recognition, but don't allow out of the box new spotting words without building the model again.

**Comment by nshmyrev** [comment]
Kaldi can spot words even more effectively than sphinx. We will probably update that part soon.

**Comment by abouquet** [comment]
> Kaldi can spot words even more effectively than sphinx. We will probably update that part soon.

Do you have an ETA on that ? Because I need to implement this before summer ...

**Comment by abouquet** [comment]
Ok, my issue of slow initialization was that I was also trying to reload jni bridge along side with assets files.
It's indeed quicker to only recreate a `SpeechRecognizer` (but keep a reference to a `Model` seems to be ok)

So, if we should create it, what is the purpose of `pause()` / `stop()` method ?

**Comment by nshmyrev** [comment]
> So, if we should create it, what is the purpose of pause() / stop() method ?

Say if if activity is paused  and user switched to another activity you need to pause speech recognizer.

**Comment by abouquet** [comment]
Ok, Ive put it into a Service, that's why I don't need it :)

But for the activity, I don't get what it does internally. Does it free some memory ? I thought we just have to dispose it and instantiate it again to do that.

**Comment by nshmyrev** [comment]
> But for the activity, I don't get what it does internally. Does it free some memory ? I thought we just have to dispose it and instantiate it again to do that.

Hm, indeed. It was more relevant for pocketsphinx when startup was slow. Actually if you keep the recognizer some speaker adaptation remains in place so it might be a good idea to pause instead. We might need to test/design this part.

It is all possible to change, we just need to understand better the requirements and workflow.

**Comment by nshmyrev** [comment]
For keyword spotting in Kaldi see https://github.com/alphacep/vosk-api/issues/55, one has to compile a graph with the target words and alternatives and [unk] phone loop. With this graph the recognizer will spot even better than pocketsphinx.

**Comment by abouquet** [comment]
> Hm, indeed. It was more relevant for pocketsphinx when startup was slow. Actually if you keep the recognizer some speaker adaptation remains in place so it might be a good idea to pause instead. We might need to test/design this part.

I think, for `pause()` method to be implemented, we should only release recorder. Imho, that's what `pause()` is the purpose for.

**Comment by abouquet** [comment]
> For keyword spotting in Kaldi see [alphacep/vosk-api#55](https://github.com/alphacep/vosk-api/issues/55), one has to compile a graph with the target words and alternatives and [unk] phone loop. With this graph the recognizer will spot even better than pocketsphinx.

ok, I think, this is also related with https://github.com/alphacep/kaldi-android-demo/issues/18

**Comment by nshmyrev** [comment]
Lets track at https://github.com/alphacep/kaldi-android-demo/issues/18
