### ISSUE TITLE
Record Audio while Recognition in progress

### ISSUE THREAD

**Issue by abouquet** [alphacep/vosk-android-demo#51]
I would like to be able to record audio at the same time I'm doing recognition.
Is it possible to implement that ? 

I've also done it on sphinx implementation side, but I would like to be able to do it in Kaldi.
The need is to be able to validate recognition against audio files.

**Comment by abouquet** [comment]
It's maybe related to https://github.com/alphacep/kaldi-android-demo/issues/16

**Comment by nshmyrev** [comment]
Lets track it in #16
