### ISSUE TITLE
Question: What is the purpose of words.txt file in model

### ISSUE THREAD

**Issue by lemberh** [alphacep/vosk-android-demo#58]
I have one question what is the purpose of this file in model https://github.com/alphacep/vosk-android-demo/blob/master/models/src/main/assets/sync/model-android/words.txt
As it is absent in standalone models here https://github.com/alphacep/vosk-api/blob/master/doc/models.md

**Comment by nshmyrev** [comment]
words.txt contains mapping from integer ids used internally to word strings. It is not really necessary since this symbol table is usually packed inside the Gr.fst as in https://github.com/alphacep/vosk-api/blob/master/doc/adaptation.md
