### ISSUE TITLE
Warn about OOV words in the grammar and reject recognition

### ISSUE THREAD

**Issue by lemberh** [alphacep/vosk-android-demo#59]
When setting grammar speech recognition is not working
`new KaldiRecognizer(model, 16000.0F, "voltar proximo entrada intervalo trabalho")`
I'm getting this error and no text in result
>W/VoskAPI: OutputArcForce():word-align-lattice.cc:578) Invalid word at end of lattice [partial lattice, forced out?]

**Comment by nshmyrev** [comment]
Try próximo instead of proximo

**Comment by lemberh** [comment]
Thanks!
That fixed the problem
