### ISSUE TITLE
Receiving result when there is no audio input

### ISSUE THREAD

**Issue by lemberh** [alphacep/vosk-android-demo#62]
When listening to audio stream with grammar filter, for example:
`new KaldiRecognizer(model, 16000.0F, "voltar próximo entrada intervalo trabalho")`
Sometimes when there is silence I'm receiving the last word as a result. And this always happens without receiving **partialResult**.

**Comment by nshmyrev** [comment]
Add '[unk]' to that list, it should help.

**Comment by lemberh** [comment]
Thank you!
That has fixed the problem
