### ISSUE TITLE
whether the aar in this demo supports the model which is trained without ivector or not

### ISSUE THREAD

**Issue by Nie-Yingying** [alphacep/vosk-android-demo#64]
Hi, 
when I compile my own model which is no ievctor as input, the apk can be builded successufully, but  it always forced termination at once when opened. And my model can be runned with other decoding ways. So I suspend that the aar is not the one which support kaldi model without ivector.

In the path ./models/src/main/assets/sync/model-android, there is mfcc.conf, words.txt, final.mdl, disambig_tid.int, HCLr.fst and Gr.fst. And the 'ivector' directory is deleted. 

Thanks for your attention!

**Comment by nshmyrev** [comment]
I have just pushed an updated AAR, it should work now. Update and try again please. Feel free to reopen if needed.

**Comment by Nie-Yingying** [comment]
It works well. 

Thank you so much!
