### ISSUE TITLE
Handle kaldi exception

### ISSUE THREAD

**Issue by aleksandrmozgovoi** [alphacep/vosk-android-demo#65]
Hi
I dynamically download a model from the Internet to an sd card
If the model is intact and the files are not damaged, then everything is fine, it works.
But if you specify the wrong path when creating the model or if there are no files there, then the application closes.

I cannot handle this error since it comes from jni.

Are there any ways to handle the error or verify the integrity of the model before creating it?

Thanks, have a nice day

```
 pid: 20696, tid: 20728, name: AsyncTask #1  >>> org.kaldi.demo <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError'
```

**Comment by nshmyrev** [comment]
You can check md5 sums before running recognizer like we are doing in our Assets class.

**Comment by aleksandrmozgovoi** [comment]
Yes, I saw how the example is checked, I thought about it, but it complicates the code.
For each model and each version it will be necessary to store md5

**Comment by nshmyrev** [comment]
There is no other way we check the model is complete. If some files are missing it will crash on later stage, not just on load.
