### ISSUE TITLE
Pause recognition

### ISSUE THREAD

**Issue by aleksandrmozgovoi** [alphacep/vosk-android-demo#67]
Hi
I recognize commands and respond with textToSpeach.
While the phone answers me, it recognizes this text again. I have a callback for the end of the pronunciation of the text and I could turn off recognition for this time.

I need a pause and resume recognition that can work quickly.
Is there such a way? I searched a bit and did not find a method.
Thanks for your work.

**Comment by nshmyrev** [comment]
SpeechRecognizer method has `stop`/`cancel` and `startListening `methods. They should work. `stop` will return one more result, `cancel` will stop without result.

**Comment by abouquet** [comment]
@aleksandrmozgovoi , I had the same requirement and couldn't `stop` / `start` with a certain lag and sometime a crash.

I don't know if it was from my code, but I ended up into managing a mute boolean on the microphone when tts was speaking.

To achieve that :

- [ ] add a `UtteranceProgressListener` on your `TextToSpeech` instance
- [ ] `setMicrophoneMute(true)` on your `AudioManager` instance on UtteranceProgressListener.onStart()
- [ ] `setMicrophoneMute(false)` on your `AudioManager` instance on UtteranceProgressListener.onDone()
- [ ] don't forget to add `<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>` on your `AndroidManifest.xml`

**Comment by nshmyrev** [comment]
We have implemented SpeechService.setPause method:

https://github.com/alphacep/vosk-api/blob/2221cd02094ff2f64c1707713f6a9b203cf78a68/android/lib/src/main/java/org/vosk/android/SpeechService.java#L146

**Comment by abouquet** [comment]
you nailed it. Will change my workaround to safe mobile resources ;)
