### ISSUE TITLE
Cannot recognise words in the demo

### ISSUE THREAD

**Issue by Sadeen** [alphacep/vosk-android-demo#69]
Hi,

Thank you for this nice demo. I run the demo successfully, however, when I press "Recognize Microphone" its start showing "{ partial } ...." and keep doing this.

How I can run the recognizer successfully?

Thanks

Best,

**Comment by abouquet** [comment]
@Sadeen , if you are using emulator, along side activating audio recording permission, make sure to tick record from microphone capability in the emulator.
It's always deactivated my default each time emulator is restarting.

I had the same issue as you in the beggining, and it's now working fine

![image](https://user-images.githubusercontent.com/2518542/84586259-2b78b300-ae18-11ea-8397-d761025ec2ab.png)
