### ISSUE TITLE
App Crash on Nexus 6P (not enough memory for huge model)

### ISSUE THREAD

**Issue by gunjanddave** [alphacep/vosk-android-demo#70]
The app is crashing while preparing for the recognizer. But no error in logs. For One Plus 5, Pixel is working fine.
App crashes and in the log this is the last line in the log
org.kaldi.demo I/VoskAPI: ReadDataFiles():src/model.cc:233) Loading HCLG from /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/graph/HCLG.fst

**Comment by nshmyrev** [comment]
Maybe the data files are corrupted, delete them and try again. Btw, our default demo models don't have HCLG.fst, it should be your custom model. Try with default one first.

**Comment by gunjanddave** [comment]
@nshmyrev  Yes default one is working and even custom is working with other devices apart from Nexus. Do you suggest a model with takes commands and works with accuracy instead of dictation?

**Comment by nshmyrev** [comment]
> Do you suggest a model with takes commands and works with accuracy instead of dictation?

No, I didn't say anything like that.

**Comment by gunjanddave** [comment]
I think for some devices where it is crashing for **some devices** this package 'libc++_shared.so' is missing in the APK file.

**Comment by nshmyrev** [comment]
> like nexus is because this package 'libc++_shared.so' is missing in the APK file. 

Thanks, how do you figure out that? It doesn't seem we require libc++, you can check here:

 ```
readelf --dynamic libkaldi_jni.so  | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [liblog.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
```

**Comment by gunjanddave** [comment]
As I am not seeing any logs with the crash. It is my assumption based on this Kaldi blog post where it says maybe for some devices share.so would be required.

http://jcsilva.github.io/2017/03/18/compile-kaldi-android/

<img width="924" alt="Screenshot 2020-06-14 at 9 57 02 AM" src="https://user-images.githubusercontent.com/36508093/84584733-81078c80-ae25-11ea-9a03-99a8e29c11c5.png">

**Comment by nshmyrev** [comment]
> my assumption based on this Kaldi blog post where it says maybe for some devices share.so would be required.

We compile libc++ statically, so this is not very relevant.

As for crash, please provide full logcat message from application start.

**Comment by gunjanddave** [comment]
Logs of the app from start. The same app is working on Samsung, One Plus, Lenovo, Pixel. I am using [https://github.com/daanzu/kaldi-active-grammar/releases/download/v1.4.0/vosk-model-en-us-daanzu-20200328.zip](Model) I know it is huge size model. But if it is working on other devices it should work on Nexus.
**Logs**

```
06-14 10:12:51.884 2190-2190/? I/art: Late-enabling -Xcheck:jni
06-14 10:12:52.116 2190-2190/org.kaldi.demo E/MultiWindowProxy: getServiceInstance failed!
06-14 10:12:52.230 2190-2190/org.kaldi.demo I/[MALI][Gralloc]: [+]r_hnd:0x7f8e148980, fd:25, ion_hnd(0x1), req_format(0x1), int_fmt(0x1)  byte_stride(4096), flags(0x4), usage(0x100), size(8388608), alloc_size(8388608) 1024(1024)X2048(2048) pid(2190)  sec (0)
06-14 10:12:52.293 2190-2214/org.kaldi.demo I/OpenGLRenderer: Initialized EGL, version 1.4
06-14 10:12:52.299 2190-2214/org.kaldi.demo I/OpenGLRenderer: Get enable program binary service property (0)
06-14 10:12:52.299 2190-2214/org.kaldi.demo W/OpenGLRenderer: Program binary service is not enabled.
06-14 10:12:52.304 2190-2214/org.kaldi.demo W/libEGL: [ANDROID_RECORDABLE] format: 1
06-14 10:12:52.374 2190-2214/org.kaldi.demo I/[MALI][Gralloc]: [+]r_hnd:0x7f8e149880, fd:35, ion_hnd(0x2), req_format(0x1), int_fmt(0x1)  byte_stride(2880), flags(0x4), usage(0xb00), size(3686400), alloc_size(3686400) 720(720)X1280(1280) pid(2190)  sec (0)
06-14 10:12:52.473 2190-2214/org.kaldi.demo I/[MALI][Gralloc]: [+]r_hnd:0x7f8e1497e0, fd:37, ion_hnd(0x3), req_format(0x1), int_fmt(0x1)  byte_stride(2880), flags(0x4), usage(0xb00), size(3686400), alloc_size(3686400) 720(720)X1280(1280) pid(2190)  sec (0)
06-14 10:12:53.854 2190-2214/org.kaldi.demo I/[MALI][Gralloc]: [+]r_hnd:0x7f8e149920, fd:36, ion_hnd(0x4), req_format(0x1), int_fmt(0x1)  byte_stride(2880), flags(0x4), usage(0xb00), size(3686400), alloc_size(3686400) 720(720)X1280(1280) pid(2190)  sec (0)
06-14 10:17:55.073 2190-2213/org.kaldi.demo I/VoskAPI: ConfigureV2():src/model.cc:175) Decoding params beam=13 max-active=7000 lattice-beam=6
06-14 10:17:55.073 2190-2213/org.kaldi.demo I/VoskAPI: ConfigureV2():src/model.cc:178) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
06-14 10:17:56.673 2190-2213/org.kaldi.demo I/VoskAPI: RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
06-14 10:17:56.673 2190-2213/org.kaldi.demo I/VoskAPI: RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
06-14 10:17:56.675 2190-2213/org.kaldi.demo I/VoskAPI: Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
06-14 10:17:57.345 2190-2213/org.kaldi.demo I/VoskAPI: CompileLooped():nnet-compile-looped.cc:345) Spent 0.349242 seconds in looped compilation.
06-14 10:17:57.345 2190-2213/org.kaldi.demo I/VoskAPI: ReadDataFiles():src/model.cc:219) Loading i-vector extractor from /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/ivector/final.ie
06-14 10:17:57.637 2190-2213/org.kaldi.demo I/VoskAPI: ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
06-14 10:17:58.304 2190-2213/org.kaldi.demo I/VoskAPI: ComputeDerivedVars():ivector-extractor.cc:204) Done.
06-14 10:17:58.305 2190-2213/org.kaldi.demo I/VoskAPI: ReadDataFiles():src/model.cc:233) Loading HCLG from /storage/emulated/0/Android/data/org.kaldi.demo/files/sync/model-android/graph/HCLG.fst
```

**Comment by nshmyrev** [comment]
Ok, does it work with our small model please?

**Comment by nshmyrev** [comment]
You should try lgraph model on mobile device at least.

**Comment by gunjanddave** [comment]
> You should try lgraph model on mobile device at least.

lGraph is working on Nexus.

**Comment by gunjanddave** [comment]
> You should try lgraph model on mobile device at least.

Yes it is working

**Comment by nshmyrev** [comment]
Ok, you don't have to run that huge models on device seriosly. Lgraph has same accuracy than big one, just a bit slower.

Nexus 6P has big problems with memory since it only has 3Gb RAM total:
https://www.reddit.com/r/AndroidPreviews/comments/6cwx9z/high_ram_usage_nexus_6p/

**Comment by nshmyrev** [comment]
Please reopen if you have further issues.
