### ISSUE TITLE
Reduce apk size

### ISSUE THREAD

**Issue by Anshul1507** [alphacep/vosk-android-demo#71]
Hi @nshmyrev, thanks for this wonderful model and demo. I have one doubt related to size of demo apk, which is crossing 50+mb size before integration this to my production app. 
My app usage is only for English model, is there any option to reduce apk size by removing other languages models as mentioned in readme?

**Comment by nshmyrev** [comment]
English model alone is 36Mb. You can download it from the webserver, then you can exclude model from the apk. 

Or if you use reduced vocabulary you can recompile Gr.fst, that will not take 20Mb.

**Comment by abouquet** [comment]
Hi @Anshul1507 

If your objective is to reduce APK size, you could maybe build platform variant separatly.
As for now, example project build APK for all variant, and JNI binding can also take some extra space per platform.
You can reduce this APK by four time if you'r doing that, that's what I also have to do on my side.

**Comment by nshmyrev** [comment]
> As for now, example project build APK for all variant, and JNI binding can also take some extra space per platform.

The JNI inside APK is just 11Mb, not that much to cover maintenance, but thank you for advise, maybe we can do it one day.

**Comment by abouquet** [comment]
@nshmyrev , this project is a demo project showing capabilities of Kaldi on Android.
Letting it as simple as it is is good enought for that purpose.

I think reducing size and specifying build for each platform is more likely a fine tuning on specific application that use Kaldi AAR.
That's why i'm not asking you to customize platform dependent builds, but only showing a possible direction to cover @Anshul1507  needs :-)

**Comment by Anshul1507** [comment]
Thank you guys, @abouquet @nshmyrev , I'll try it as you mentioned. 👍 
[Will close this issue soon when i able to solve this issue]

**Comment by Anshul1507** [comment]
So, final conclusion comes out to be store the model on server to reduce the size of apk as mentioned by @nshmyrev on telegram.  👍

**Comment by IceFloe** [comment]
@nshmyrev We need to use reduced vocabulary, do you have any tutorial which helps us to recompile model and reduce size?

**Comment by IceFloe** [comment]
I have found an instruction how to do that, thank you https://alphacephei.com/vosk/adaptation
