### ISSUE TITLE
Conflicts between org.Kaldi.SpeechRecognizer and Android's MediaRecorder

### ISSUE THREAD

**Issue by DiptarkBose** [alphacep/vosk-android-demo#73]
Hi @nshmyrev .

I wish to use android's MediaRecorder library in conjunction with Kaldi to find more insights like amplitude, frequency, etc. But when I try using MediaRecorder, a conflict arises. Both MediaRecorder and Kaldi's SpeechRecognizer try to access the same mic, and thus results in a conflict. 

1. I wanted to know, is Kaldi's SpeechRecognizer customizable? If yes, how do I go about it?

2. Android has its own SpeechRecognizer class. Is Kaldi's SpeechRecognizer related to Android's SpeechRecognizer? If yes, which file should I be exploring to understand the correlation? 

3. Where are the methods of `onResult(String hypothesis)` and `onPartialResult(String hypothesis)` defined? I just see that they are overriden in the main Java file, but am curious where they are instantiated?

Thanks in advance for your help!

**Comment by nshmyrev** [comment]
> Both MediaRecorder and Kaldi's SpeechRecognizer try to access the same mic, and thus results in a conflict.

Yes, it is long standing android problem that you can't record from multiple points.

>  I wanted to know, is Kaldi's SpeechRecognizer customizable? If yes, how do I go about it?

Yes, sure, it is open source so you can modify it according to your needs: https://github.com/alphacep/vosk-api/blob/master/android/src/main/java/org/kaldi/SpeechRecognizer.java

You can add extra methods to output amplitude and whatever else you want inside the class. If 
you feel those changes will be useful for others feel ree to submit a pull request.

> Android has its own SpeechRecognizer class. Is Kaldi's SpeechRecognizer related to Android's Speech Recognizer? If yes, which file should I be exploring to understand the correlation?

Explore our Vosk one linked above

> Where are the methods of onResult(String hypothesis) and onPartialResult(String hypothesis) defined? I just see that they are overriden in the main Java file, but am curious where they are instantiated?

"Instantiated" is the wrong word here, it is not c++. You can check https://github.com/alphacep/vosk-api/blob/master/android/src/main/java/org/kaldi/RecognitionListener.java

**Comment by DiptarkBose** [comment]
Thanks for such a clear explanation @nshmyrev !
Will be a raising a Pull request upon completion. Closing this issue out. Thanks again!
