### ISSUE TITLE
换中文vosk-model-small-cn-0.3模型问题

### ISSUE THREAD

**Issue by PeterLocas** [alphacep/vosk-android-demo#77]
我将vosk-model-small-cn-0.3 解压后替换项目中的ivector的文件，运行后报错

02-24 01:05:47.021 4138-4138/org.kaldi.demo V/SettingsInterface: invalidate [system]: current 37 != cached 0
02-24 01:05:47.024 4138-4138/org.kaldi.demo D/ActivityThread: holder:android.app.IActivityManager$ContentProviderHolder@a681640, holder.provider:android.content.ContentProviderProxy@a992979
02-24 01:05:47.039 4138-4138/org.kaldi.demo E/VoskAPI: OnlineTransform():online-feature.cc:533) Dimension mismatch: source features have dimension 91 and LDA #cols is 281
02-24 01:05:47.043 4138-4138/org.kaldi.demo E/libc++abi: terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError
    
    --------- beginning of crash
02-24 01:05:47.043 4138-4138/org.kaldi.demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 4138 (org.kaldi.demo)

**Comment by nshmyrev** [comment]
> 解压后替换项目中的ivector的文件

不要那样做 ;) 保持模型文件不变

**Comment by PeterLocas** [comment]
@nshmyrev  thank you i will try

**Comment by PeterLocas** [comment]
@PeterLocas 直接删除model-android 下的所有文件，再替换即可
