### ISSUE TITLE
'{"partial" : ""} part

### ISSUE THREAD

**Issue by ekremsahin** [alphacep/vosk-android-demo#81]
Hi,

First of all thanks for this amazing project it helps me very much. So i want to remove '**{"partial" : ""}**' this part from each microphone recognition iteration. i need to see only what i say when microphone recognition. For example if i say "come here" i need to see "come here" in the textView. Is there any way to do it? I search android demo code but i cant find a way to do it. 

Thanks for help. Have a good day.

**Comment by nshmyrev** [comment]
You parse string with json parser and then ignore the result object if it has partial field.

**Comment by ekremsahin** [comment]
Thanks for Help

**Comment by CaydenPierce** [comment]
This should probably be updated to pass a JSONObject or a library native transcript object, but not really a big deal.

To do as @nshmyrev said:
```
@Override
public void onResult(String hypothesis) {
   try {
            JSONObject voskResponse = new JSONObject(hypothesis);
            String transcript = voskResponse.getString("text");
        } catch (JSONException e){
            e.printStackTrace();
        }
}
```
