### ISSUE TITLE
Loop in microphone recognizing

### ISSUE THREAD

**Issue by ekremsahin** [alphacep/vosk-android-demo#82]
Hi Again Nickolay :)

I am trying to do that when i say a certain word like "register contact", the app waits for my next commands to take name and phone number information. First, i was try to do that by using while loop but it stops main thread and my app crushed. Do you know a way to do that? Is there a method to do that in vosk libraries? 

Thanks for help, have a good day

**Comment by nshmyrev** [comment]
You can implement something like state machine and simply analyze current state in the callback.

**Comment by ammyt** [comment]
check out the pocketsphinx android demo, I was able to achieve this by building something similar to that

**Comment by nshmyrev** [comment]
Feel free to reopen if you need more help.
