### ISSUE TITLE
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: C:\model/mfcc.conf

### ISSUE THREAD

**Issue by oussaifi-majdi** [alphacep/vosk-android-demo#86]

**Comment by nshmyrev** [comment]
Wrong package

**Comment by oussaifi-majdi** [comment]
i want to use speech to text and i download this model https://alphacephei.com/vosk/models/vosk-model-small-fr-pguyot-0.3.zip

**Comment by oussaifi-majdi** [comment]
![gt](https://user-images.githubusercontent.com/31904454/90321893-3e118480-df4e-11ea-8f53-bdc4dfaad04b.PNG)
