### ISSUE TITLE
Have some questions related the input file format

### ISSUE THREAD

**Issue by meenakshi17media** [alphacep/vosk-android-demo#87]
My questions are :

1. Is it mandatory to use .wav file as an input ?
2. can we use .mp3 or .flv audio files ? 
3. is there any time duration of audio file defined for 1 input ?
4. is there any pre-processing steps for input audio file.

I passed a random 1 minute .mp3 audio file as an input but getting wrong results.

**Comment by nshmyrev** [comment]
> Is it mandatory to use .wav file as an input ?

Yes, and the wav file must be in specific format.

> can we use .mp3 or .flv audio files ?

You have to convert first with ffmpeg for example

> is there any time duration of audio file defined for 1 input ?

No

> is there any pre-processing steps for input audio file.

No

**Comment by meenakshi17media** [comment]
ok, if i directly convert .mp3 in .wav file by using online tools, it will not work right ?

**Comment by nshmyrev** [comment]
> ok, if i directly convert .mp3 in .wav file by using online tools, it will not work right ?

Yes

**Comment by meenakshi17media** [comment]
i am not able to use 

vosk-model-small-en-us-0.3 | 36M | TBD | Lightweight wideband model for Android and RPi
-- | -- | -- | --

this model in android giving error : 
   Result %s elapsed %d milliseconds

I am giving .wav file converted by ffmpeg audio file

**Comment by nshmyrev** [comment]
Make sure audio file has proper format - 16 khz 16 bit mono signed pcm.

**Comment by meenakshi17media** [comment]
In small model for android you don't have model.conf file, you mentioned in your document that : 

conf/model.conf - provide default decoding beams and silence phones. you have to create this file yourself, it is not present in kaldi model

can you help me with this, so i can build model.conf file for android speech to text feature.
And the solution you provided for STT its based pre-defined grammar or keyword or it will work without sending grammer also.

can you help me with this, i am an android person, don't have that much knowledge about kaldi and all models things.

Thanks in Advance
