### ISSUE TITLE
Several languages

### ISSUE THREAD

**Issue by SeriousW** [alphacep/vosk-android-demo#88]
Hello. How can I use several models in one project? There is some instruction?

**Comment by nshmyrev** [comment]
Just create several Model objects and use them.

**Comment by SeriousW** [comment]
Thanks! But how I should generate file with .md5 extension and where file "words" in Russian model?

![Снимок экрана 2020-08-27 в 10 57 18](https://user-images.githubusercontent.com/57483622/91413732-373f1780-e854-11ea-91ec-afddd089cd88.png)

**Comment by nshmyrev** [comment]
> But how I should generate file with .md5 extension and 

md5 files are created automatically on build with https://github.com/alphacep/vosk-android-demo/blob/49a353448255234bc90741f130e42a2c16c14519/models/build.gradle#L14

> where file "words" in Russian model?

It is optional

**Comment by SeriousW** [comment]
Thanks for quick answer!

**Comment by nshmyrev** [comment]
Ok, feel free to reopen if you have further questions?
