### ISSUE TITLE
Need help in Android small model configurations for STT

### ISSUE THREAD

**Issue by meenakshi17media** [alphacep/vosk-android-demo#90]
In small model for android you don't have model.conf file, you mentioned in your document that :

conf/model.conf - provide default decoding beams and silence phones. you have to create this file yourself, it is not present in kaldi model

can you help me with this, so i can build model.conf file for android speech to text feature.
And the solution you provided for STT its based pre-defined grammar or keyword or it will work without sending grammer also.

can you help me with this, i am an android person, don't have that much knowledge about kaldi and all models things.

Thanks in Advance

**Comment by nshmyrev** [comment]
> In small model for android you don't have model.conf file, you mentioned in your document that :

In which one exactly?

**Comment by meenakshi17media** [comment]
vosk-model-small-en-us-0.3, this one, i have to implement this in android for stt.

**Comment by nshmyrev** [comment]
I suppose this issue is not relevant anymore.
