### ISSUE TITLE
Is recongnize file only recognizing numbers in a .wav file?

### ISSUE THREAD

**Issue by liuyibox** [alphacep/vosk-android-demo#91]
>  rec = new KaldiRecognizer(activityReference.get().model, 16000.f, "oh zero one two three four five six seven eight nine");
> 
> InputStream ais = activityReference.get().getAssets().open("10001-90210-01803.wav");

The `10001-90210-01803.wav` only contains numbers, `rec.AcceptWaveform` can recognize those numbers. However, if I record a wav file speaking both English words and numbers, the `RECOGNIZE FILE` button can only return the transcription of the numbers part but ignore the English words part, is this true for `RECOGNIZE FILE`?

If I only want to transcript the wav/pcm containing both English words and numeric numbers, i.e., I do not use the microphone, how should I implement this file transcription? In this case,  do I have to look into your source wrapper code  `speechService.addListener` and `speechService.startListening` for this task?

**Comment by nshmyrev** [comment]
If you create recognizer without word hints, it will recognize both words and numbers:

`rec = new KaldiRecognizer(activityReference.get().model, 16000.f);`

**Comment by liuyibox** [comment]
Thanks. I created the recognizer without word hints. It seems that this issue is caused by the fact that `rec.AcceptWaveform` sometimes automatically ignore or perform badly for first several seconds of wav recording content. This leads to the fact that I need to cautiously wait for 1~2 seconds and speak loudly to make sure all the content can be transcripted appropriately. If I adjust my speaking in this way. The transcripted result seems acceptable to me so far.
