### ISSUE TITLE
Documentation: add some howto to build an adroid apk

### ISSUE THREAD

**Issue by mwellnitz** [alphacep/vosk-android-demo#92]
Hello,
I want to do some tests with vosk-android as /e/ doesn't have any tts-engine.
My Knowledge in building Android apps are somewhat limited.
It would be nice to have a step-by-step Howto-Build-Android-APK eg. for plain Ubuntu installation.
Thanks, Marcus

**Comment by nshmyrev** [comment]
1. Checkout project from github
2. Import into Android Studio
3. Build an APK

Thats it
