### ISSUE TITLE
FDroid: Multi-language android tts vosk .akp

### ISSUE THREAD

**Issue by mwellnitz** [alphacep/vosk-android-demo#93]
Hello,
would be nice to have a multi-language Android .apk tts engine.
Some distributions like are lack of tts-engine. Als many apps need an tts-engine it'e a pain. A multilanguage vosk-package on FDroid would be nice.
Thanks, Marcus

**Comment by nshmyrev** [comment]
vosk is for speech recognition, sorry, not for tts. Do you need speech synthesis (tts) or speech recognition (vosk, stt)?

**Comment by mwellnitz** [comment]
Hi Nickolay,
thanks for your reply. I need tts so I have to look for an other solution.
Thanks for invest in that great project.
Marcus
