### ISSUE TITLE
Result view

### ISSUE THREAD

**Issue by lavrenkov-sketch** [alphacep/vosk-android-demo#99]
Hi, I only need to output` result.text `value how do I rewrite` recognizeMicrophone()` so that it can do this???

**Comment by nshmyrev** [comment]
parse string with json parser and extract text

**Comment by lavrenkov-sketch** [comment]
@nshmyrev 
my code it doesn't output anything, where is the error here?

`    @Override
    public void onResult(String hypothesis) {
                try {
                    JSONObject jsonObject = new JSONObject(hypothesis);
                    JSONObject songs= jsonObject.getJSONObject("text");
                    resultView.append(songs.toString() + "\n");
                }catch (JSONException e) {
                    System.out.println(e.getMessage());
        }
    }`

**Comment by nshmyrev** [comment]
It should be `jsonObject.getJSONObject("result").getJSONObject("text")` with extra checks for null.
